### ISSUE TITLE
Gallery page order controlled via configuration

### ISSUE THREAD

**Issue by riccardoporreca** [riccardoporreca/rmdgallery#15]
The metadata of the various gallery pages are currently sorted according to the file-name their are defined in and how they appear within metadata files. We should support an explicit ordering based onthe metadata fields, including support for descending order, with something like:
```yaml
gallery:
  order_by: [desc(author), title, ...]
```

When implement this we should include a nice feature: the metadata fields should include the page name itself, which otherwise is only the name of the page metadata in the list. This should be added as `page_name` when the metadata are processed.
```yaml
foo:
  title: Foo
  menu_entry: Oof
  page_name: foo
bar:
  title: Bar
  menu_entry: Rab
  page_name: bar
```
Besides this being a nice feature per se, it allows using `page_name` as default for `gallery$order_by`
