### ISSUE TITLE
Allow defining menu icons in the metadata

### ISSUE THREAD

**Issue by riccardoporreca** [riccardoporreca/rmdgallery#16]
Metadata for gallery pages allow defining a `menu_entry` field for the gallery navbar dropdown menu.

Similarly, a `menu_icon` should be supported, so that `menu_entry` and `menu_icon` are used as `text` and `icon` when defining the gallery dropdown.

We can in fact support both the following forms

```yaml
menu_item: A gallery page
menu_icon: fa-gear
```
```yaml
menu_item:
  text: A gallery page
  icon: fa-gear
```
