### ISSUE TITLE
Allow default fields

### ISSUE THREAD

**Issue by riccardoporreca** [riccardoporreca/rmdgallery#3]
The `gallery` site configuration should allow specifying a default template, used if no page-specific `template` metadata is defined.

This could be done in a ~~forward-looking~~ more genera way, defining a new field in the `gallery` site configuration, along the lines of
``` yaml
gallery:
  defaults:
    template: embed-url
```
~~so that this can be used in the future~~ allowing to define defaults for other fields.
