### ISSUE TITLE
Allow defining custom "types" mapped to actual templates

### ISSUE THREAD

**Issue by riccardoporreca** [riccardoporreca/rmdgallery#4]
Templates used for creating each page are specified with the `template` field in the metadata and the values refer to generic, pretty technical ways of embedding content (`embed-html`, `embed-url`, ...). 

It would be convenient to allow specifying a custom website-specific field (e.g. `type`) instead, defined in the `gallery` site configuration, where custom values (e.g., `shiny`) are mapped to actual templates. Something like:
```yaml
gallery:
  type_field: type
  type_template:
    shiny: embed-url
    webpage: embed-url
    gist: embed-html
```

This can be particularly useful for galleries with user-contributed pages and metadata, where less-technical, context-specific types would be more informative.
